WebPage/project/web/views/main_views.py
from flask import Blueprint, render_template, redirect, url_for, session, g, request,jsonify, flash
from ..db import WebProject, exp_manager
from datetime import date
import json
import random

bp = Blueprint('main', __name__, url_prefix='/')
wp = WebProject.instance()
em = exp_manager.instance()

@bp.route('/', methods = ['GET', 'POST'])
def main_page():
    if(request.method=="POST"):
        params = request.get_json()
        if(params["func"]=="store"):
            today = date.today().isoformat()
            act = "todo_complete" if params["is_complete"] else "todo_write"

            send = {"can_exp" : False, "exp" : 0}

            is_exists = wp.send_query("SELECT EXISTS (SELECT * FROM todo WHERE user_id = '{}' AND nth = {} AND date = '{}') AS success".format(g.user["user_id"], params["nth"], today))
            print(act)
            if(is_exists[0]["success"]):
                wp.send_query("UPDATE todo SET content='{}', is_complete={} WHERE user_id = '{}' AND nth = {} and date = '{}'".format(params["content"], params["is_complete"], g.user["user_id"], params["nth"], today), commit=True)
                if(act=="todo_complete"):
                    print("성공 exp 얻기")
                    send["can_exp"] = em.gain_exp(g.user["user_id"], act)
                    if(send["can_exp"]):
                        send["exp"] = em.exp_dict[act]
            else:
                wp.send_query("INSERT INTO todo(user_id, is_complete, content, nth, date) VALUES ('{}', {}, '{}', {}, '{}')".format(g.user["user_id"], params["is_complete"], params["content"], params["nth"], today), commit=True)
                if(act=="todo_write"):
                    print("작성 exp 얻기")
                    send["can_exp"] = em.gain_exp(g.user["user_id"], act)
                    if(send["can_exp"]):
                        send["exp"] = em.exp_dict[act]

        
        
        elif(params["func"]=="get"):
            send = wp.send_query("""WITH test AS
                (
                    SELECT 0 AS nth
                    UNION ALL
                    SELECT 1 AS nth
                    UNION ALL
                    SELECT 2 AS nth
                    UNION ALL
                    SELECT 3 AS nth
                    UNION ALL
                    SELECT 4 AS nth
                )
                SELECT test.nth, IFNULL(todo.is_complete, -1) AS is_complete , IFNULL(todo.content, "") AS content FROM test LEFT JOIN todo ON test.nth = todo.nth AND todo.user_id = '{}' AND todo.date = '{}' ORDER BY nth;
                """.format(g.user["user_id"], params["date"]))
        
        return json.dumps(send)
    

    log = session.get('logged_in')
    if log:
        # 로그인 중이면
        em.daily_exist(g.user["user_id"])
        main_data = {}
        # args id 가 있을 때
        if request.args.get('id'):
           back_id = request.args.get('id', type=int)
           wp.send_query("update user set background_id={} where id='{}';".format(back_id,g.user["user_id"]), commit=True)
        # args snow 가 있을 때
        elif request.args.get('snow'):
           snow_id = request.args.get('snow', type=int)
           wp.send_query("update user set snow={} where id='{}';".format(snow_id,g.user["user_id"]), commit=True)
            
        back_snow = wp.send_query("SELECT background_id, snow FROM user WHERE id = '{}'".format(g.user["user_id"]))
        back_id = back_snow[0]['background_id']
        snow_id = back_snow[0]['snow']
        
        result = wp.send_query("SELECT user_Lv, user_Exp FROM user WHERE id = '{}'".format(g.user["user_id"]))
        main_data["lv"] = result[0]["user_Lv"]
        main_data["exp"] = result[0]["user_Exp"]

        main_data["imgview"] = random.randrange(1,3)

        main_data["max_exp"] = em.lvup_dict[main_data["lv"]]
        main_data['background_id'] = back_id
        main_data['snow_id'] = snow_id
        today = date.today().isoformat()
        main_data["mission"] = wp.send_query("SELECT quest_solve FROM daily WHERE user_id = '{}' AND date = '{}'".format(g.user["user_id"], today))[0]["quest_solve"]

        two = wp.send_query('select content from notice_board')
        li = [i['content'] for i in two]
        main_data['li'] = li
        
        return render_template('main/main_page.html', main_data=main_data)
    else:
        # 로그인 정보가 없으면
        return redirect(url_for("login.login_page"))

        
@bp.route('/ranking', methods=['GET', 'POST'])
def ranking_page():
    rank_dict = {}
    number = 10
    #현재 페이지
    page = request.args.get('page', type=int, default=1)
    first_number = (page-1) *number
    last_number =  (page*number)
    ranking = wp.send_query("SELECT id, user_Lv, user_Exp FROM user ORDER BY user_Lv DESC,user_Exp DESC")
    
    max_page = (len(ranking) - 1) // number + 1

    item = ranking[first_number:last_number]
    
    rank_dict['item'] = item
    rank_dict['max_page'] = list(range(1,max_page+1))
    rank_dict['page'] = page
    for j,i in enumerate(ranking):
        if g.user['user_id'] == i['id']:
            rank_dict['myinfo'] = j+1
            rank_dict['mypage'] = int((j //10) +1)
    
    if request.method == 'POST':
        params = request.get_json()

        for ret1,ret2 in enumerate(ranking):
            te = True
            if params['value'] == ret2['id']:
                te = False
                print(ret1)
                user_page = int((ret1 //10) +1)
                data = {'user_page': user_page}
                return jsonify(data)
        if te:
            flash('다시하세요')

            return redirect(url_for('main.ranking_page'))
            

    return render_template('main/ranking_page.html',user_rank = rank_dict)


@bp.route('/gg', methods = ['GET'])
def test():

    return render_template('main/test.html', datas = data)

WebPage/project/web/views/myinfo_views.py
from flask import Blueprint, render_template, redirect, url_for, g, request, flash
from ..db import WebProject
from werkzeug.security import check_password_hash,generate_password_hash
from ..form import Trypwd, Enroll

bp = Blueprint('myinfo', __name__, url_prefix='/myinfo')
wp = WebProject.instance()


@bp.route('/')
def setting_page():
    data =g.user["user_id"]
    return render_template('myinfo/setting_page.html', data = data)

@bp.route('/passcheck', methods=['GET', 'POST'])
def password():
    form = Trypwd()
    data = g.user["user_id"]
    if request.method == 'POST' and form.validate_on_submit():
        userpw = request.form['userpw2']
        user_pwd = wp.send_query("SELECT pwd FROM user WHERE id = '{}'".format(g.user['user_id']))
        
        if check_password_hash(user_pwd[0]['pwd'],userpw):
            print('여기까지 왔다요')
            return redirect(url_for("myinfo.infomodify"))
        
        else:
            flash('비밀번호 틀림')
            return redirect(url_for("myinfo.password"))

    else:
        return render_template('myinfo/myinfo_passcheck.html', form=form, data = data)
    
@bp.route('/infomodify', methods=['GET', 'POST'])
def infomodify():
    if(request.method == 'POST'):
        params = request.get_json()
        if len(params['value']) == 0:
            flash('다시 입력해 주세요')
            return redirect(url_for("myinfo.infomodify"))
        else:
            if params['column'] == 'name':
                wp.send_query("UPDATE user SET {} = '{}' WHERE id='{}'".format(params['column'], params['value'], g.user['user_id']), commit=True)
            else:
                wp.send_query("UPDATE user SET {} = '{}' WHERE id='{}'".format(params['column'], generate_password_hash(params['value']), g.user['user_id']), commit=True)
            return redirect(url_for("myinfo.infomodify"))
    user_info = {}
    user = wp.send_query("select * from user where id='{}'".format(g.user['user_id']))
    user_info['user_name'] = user[0]['name']
    user_info['user_id'] = user[0]['id']
    user_info['user_pwd']= user[0]['pwd']
    return render_template('myinfo/myinfo_modify.html', user_info = user_info)





@bp.route('/notice', methods=['GET'])
def notice():
    notice_dict = {}
    notice = wp.send_query("SELECT * FROM notice_board ORDER BY date DESC")
    notice_dict['item'] = notice
    user = wp.send_query("select * from user where id = '{}'".format(g.user['user_id']))
    notice_dict['admin'] = user[0]['admin']
    return render_template('myinfo/myinfo_notice.html',notice = notice_dict)


@bp.route('/content/<int:content_id>', methods=['GET'])
def content(content_id):
    content_dict = {}
    
    notice = wp.send_query("SELECT * from notice_board ORDER BY date DESC")
    page_list = [i['id'] for i in notice]
    content_dict['page_list'] = page_list
    content_dict['page'] = content_id
    
    content = wp.send_query("SELECT * from notice_board where id ={}".format(content_id))
    content_dict['content'] = content[0]
    return render_template('myinfo/myinfo_notice_content.html',contented=content_dict)

# 게시글 등록
@bp.route('/enroll', methods=['GET', 'POST'])
def enroll():
    form = Enroll()
    if request.method == 'POST' and form.validate_on_submit():  
        title = request.form['title']
        content = request.form['content']
        print(title,content)
        wp.send_query("INSERT INTO notice_board(title, content) VALUES ('{}', '{}')".format(title,content), commit=True)
        
        return redirect(url_for("myinfo.notice"))
    
    else:
        return render_template('myinfo/myinfo_notice_enroll.html', form=form)
    
# 삭제
@bp.route('/delete/<int:content_id>', methods=['GET'])
def delete(content_id):
    wp.send_query("DELETE FROM notice_board WHERE id = {}".format(content_id), commit=True)
    return redirect(url_for("myinfo.notice"))


@bp.route('/modify/<int:content_id>', methods=['GET','POST'])
def modify(content_id):
    content = wp.send_query("SELECT * from notice_board where id ={}".format(content_id))
    print('modify의')
    before = [content[0]['title'],content[0]['content']]
    if request.method == 'POST':
        title = request.form['title']
        contents = request.form['content']
        after = [title, contents]
        
        if before != after:
            wp.send_query("update notice_board set title='{}', content='{}' where id={};".format(title,contents,content_id), commit=True)
            
        return redirect(url_for("myinfo.notice"))
    else:
        return render_template('myinfo/myinfo_notice_modify.html',content=content[0])

WebPage/project/web/views/quest_views.py
from flask import Blueprint, render_template, redirect, url_for, request, session, g
from ..db import WebProject, exp_manager
from markupsafe import Markup
import json

bp = Blueprint('quest', __name__, url_prefix='/quest')
wp = WebProject.instance()
em = exp_manager.instance()

@bp.route('/')
def quest_list():
    category_data = {}
    category_data["list"] = wp.send_query("SELECT category, COUNT(category) AS n FROM problem GROUP BY category ORDER BY category")
    category_data["total"] = wp.send_query("SELECT COUNT(*) AS count FROM problem")[0]["count"]

    problem_list = wp.send_query("""
    SELECT problem.id, problem.category, (CASE solved WHEN 1 THEN 'solved' WHEN 0 THEN 'solving' ELSE 'unsolved' END) as status 
    FROM problem LEFT JOIN solving ON problem.id = solving.problem_id AND user_id='{}' 
    ORDER BY problem.id
    """.format(g.user["user_id"]))
    return render_template('main/quest_list.html', category_data = category_data, problem_list = problem_list)

@bp.route('/<int:problem_id>', methods=['GET', 'POST'])
def problem_show(problem_id):
    if(request.method == "POST"):
        send = {}
        if(em.can_exp(g.user["user_id"], "quest_solve")):
            send["can_exp"] = True
            params = request.get_json()

            result = wp.send_query("SELECT CASE WHEN answer = '{}' THEN TRUE ELSE FALSE END AS success FROM {} WHERE id = {}".format(params["answer"], params["type"], params["problem_id"]))

            is_exist = wp.send_query("SELECT EXISTS (SELECT * FROM solving WHERE user_id = '{}' AND problem_id = {}) as success".format(g.user["user_id"], params["problem_id"]))

            if(is_exist[0]["success"]):
                wp.send_query("UPDATE solving SET solved = {} WHERE user_id = '{}' AND problem_id = {}".format(result[0]["success"], g.user["user_id"], params["problem_id"]), commit=True)
            else:
                wp.send_query("INSERT INTO solving(solved, user_id, problem_id) VALUES ('{}', '{}', {})".format(result[0]["success"], g.user["user_id"], params["problem_id"]), commit=True)
            
            send["success"] = result[0]["success"]
            if(send["success"]):
                send["exp"] = em.exp_dict["quest_solve"]
                em.gain_exp(g.user["user_id"], "quest_solve")
            else:
                send["exp"] = 0

        else:
            send["can_exp"] = False
            send["success"] = 0
            send["exp"] = 0
        
        return json.dumps(send)

            
    problem_data = {}

    problem_data["status"] = wp.send_query("""
    SELECT (CASE solved WHEN 1 THEN 'solved' WHEN 0 THEN 'solving' ELSE 'unsolved' END) as status 
    FROM problem LEFT JOIN solving ON problem.id = solving.problem_id AND user_id = '{}' WHERE id = '{}'
    """.format(g.user["user_id"], problem_id))[0]["status"]

    problem_type = wp.send_query("SELECT type FROM problem WHERE id = {0}".format(problem_id))[0]["type"]
    if(problem_type=="객관식"):
        sql = "SELECT problem.*, objective.choices, objective.answer FROM problem INNER JOIN objective ON problem.id = objective.id WHERE problem.id = {}".format(problem_id)
    else:
        sql = "SELECT problem.*, subjective.answer FROM problem INNER JOIN subjective ON problem.id = subjective.id WHERE problem.id = {}".format(problem_id)
    
    problem_data["problem"] = wp.send_query(sql)[0]

    print(problem_data["problem"])

    for key, val in problem_data["problem"].items():
        if(type(val)==str):
            val = val.replace("\'\'", "\'")
            val = val.replace("\"\"", "\"")
            problem_data["problem"][key] = val
            
    # problem_data["problem"]["content"] = problem_data["problem"]["content"].replace("\n", "<br>")
    # problem_data["problem"]["explanation"] = problem_data["problem"]["explanation"].replace("\n", "<br>")

    print(problem_data["problem"])

    return render_template("main/quest_show.html", problem_data=problem_data)

WebPage/project/web/templates/exp_modal.html
{% block exp_modal %}
<link text="text/css" rel="stylesheet" href="{{ url_for('static', filename='exp_modal.css') }}">
<script defer src="{{ url_for('static', filename='exp_modal.js') }}"></script>

<div class="exp-modal">
    <div class="exp-content"></div>
        <p><label class="obtained_exp">5</label>경험치 획득!</p>
    </div>
 </div>

 <div class="level-modal">
    <div class="level-top-content">
        레벨 업!
    </div>
    <div class="level-bottom-content">
        <div class="level-chr_box">
            <img src="../static/ui/mk5.gif" class="level-modal_img">
            <img src="../static/ui/levelup.gif" class="levelup_img">
        </div>
        <p>Lv.<label class="current_lv">5</label>로 레벨업 하셨습니다.</p>
        <button class="level-modal_close">확인</button>
    </div>
 </div>

{% endblock %}

WebPage/project/web/templates/form_errors.html
{% if form.errors %}
<div class="alert alert-danger" role="alert">
    {% for field, errors in form.errors.items() %}
        <strong id = 'te'>{{ form[field].label }}</strong>
        <script> tr()</script>
    {% endfor %}
</div>
{% endif %}

{% for message in get_flashed_messages() %}
<div class="alert alert-danger" role="alert">
    <script>alert("{{message}}")</script>
</div>
{% endfor %}

WebPage/project/web/templates/frame.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">    
    <title>시연용 Frame</title>
    <style>       
        *{
            box-sizing: border-box;
        }
        
        .display {
            width: 510px;
            height: 1000px;
            position: relative;

            margin: 0;
            padding: 10px 26px;
            
            align-items: center;
        }
        
        .display::before{
            box-sizing: border-box;
            pointer-events: none;

            content:"";
            z-index: 1;

            width: 510px;
            height: 1000px;

            position: absolute;
            top: 0;
            left: 0;

            margin: 0;
            
            background-image: url("../static/ui/frame.png");
            background-size: cover;
        }

        .camera {
            z-index: 1;
            position: absolute;

            right: 50%;
            top: 23px;

            transform: translate(50%, 0);
            text-align: center;
        }

        iframe {
            padding: 10px;
            width: 100%;
            height: 100%;

            border-radius: 9%;
        }
    </style>
</head>
<body>
    <div class = "display">
        <iframe frameborder="0" width="100%" height="100%" scrolling="no"></iframe>
    </div>
    <script defer>
        document.querySelector("iframe").setAttribute("src", "http://" + location.host)
    </script>
</body>
</html>

WebPage/project/web/templates/index.html
<!DOCTYPE html>
<html lang="en-us">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title>Unity WebGL Player | web game sesac</title>
    <link rel="shortcut icon" href="{{ url_for('static', filename='TemplateData/favicon.ico') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='TemplateData/style.css') }}">
  </head>
  <body>
    <div id="unity-container" class="unity-desktop">
      <canvas id="unity-canvas" width=960 height=600></canvas>
      <div id="unity-loading-bar">
        <div id="unity-logo"></div>
        <div id="unity-progress-bar-empty">
          <div id="unity-progress-bar-full"></div>
        </div>
      </div>
      <div id="unity-warning"> </div>
      <div id="unity-footer">
        <div id="unity-webgl-logo"></div>
        <div id="unity-fullscreen-button"></div>
        <div id="unity-build-title">web game sesac</div>
      </div>
    </div>
    <script>
      var container = document.querySelector("#unity-container");
      var canvas = document.querySelector("#unity-canvas");
      var loadingBar = document.querySelector("#unity-loading-bar");
      var progressBarFull = document.querySelector("#unity-progress-bar-full");
      var fullscreenButton = document.querySelector("#unity-fullscreen-button");
      var warningBanner = document.querySelector("#unity-warning");

      // Shows a temporary message banner/ribbon for a few seconds, or
      // a permanent error message on top of the canvas if type=='error'.
      // If type=='warning', a yellow highlight color is used.
      // Modify or remove this function to customize the visually presented
      // way that non-critical warnings and error messages are presented to the
      // user.
      function unityShowBanner(msg, type) {
        function updateBannerVisibility() {
          warningBanner.style.display = warningBanner.children.length ? 'block' : 'none';
        }
        var div = document.createElement('div');
        div.innerHTML = msg;
        warningBanner.appendChild(div);
        if (type == 'error') div.style = 'background: red; padding: 10px;';
        else {
          if (type == 'warning') div.style = 'background: yellow; padding: 10px;';
          setTimeout(function() {
            warningBanner.removeChild(div);
            updateBannerVisibility();
          }, 5000);
        }
        updateBannerVisibility();
      }

      var buildUrl = "{{ url_for('static', filename='Build') }}";
      var loaderUrl = buildUrl + "/WebGame.loader.js";
      var config = {
        dataUrl: buildUrl + "/WebGame.data.unityweb",
        frameworkUrl: buildUrl + "/WebGame.framework.js.unityweb",
        codeUrl: buildUrl + "/WebGame.wasm.unityweb",
        streamingAssetsUrl: "StreamingAssets",
        companyName: "DefaultCompany",
        productName: "web game sesac",
        productVersion: "1.0.2",
        showBanner: unityShowBanner,
      };

      // By default Unity keeps WebGL canvas render target size matched with
      // the DOM size of the canvas element (scaled by window.devicePixelRatio)
      // Set this to false if you want to decouple this synchronization from
      // happening inside the engine, and you would instead like to size up
      // the canvas DOM size and WebGL render target sizes yourself.
      // config.matchWebGLToCanvasSize = false;

      if (/iPhone|iPad|iPod|Android/i.test(navigator.userAgent)) {
        // Mobile device style: fill the whole browser client area with the game canvas:

        var meta = document.createElement('meta');
        meta.name = 'viewport';
        meta.content = 'width=device-width, height=device-height, initial-scale=1.0, user-scalable=no, shrink-to-fit=yes';
        document.getElementsByTagName('head')[0].appendChild(meta);
        container.className = "unity-mobile";
        canvas.className = "unity-mobile";

        // To lower canvas resolution on mobile devices to gain some
        // performance, uncomment the following line:
        // config.devicePixelRatio = 1;

        unityShowBanner('WebGL builds are not supported on mobile devices.');
      } else {
        // Desktop style: Render the game canvas in a window that can be maximized to fullscreen:

        canvas.style.width = "960px";
        canvas.style.height = "600px";
      }

      loadingBar.style.display = "block";

      var script = document.createElement("script");
      script.src = loaderUrl;
      script.onload = () => {
        createUnityInstance(canvas, config, (progress) => {
          progressBarFull.style.width = 100 * progress + "%";
        }).then((unityInstance) => {
          loadingBar.style.display = "none";
          fullscreenButton.onclick = () => {
            unityInstance.SetFullscreen(1);
          };
        }).catch((message) => {
          alert(message);
        });
      };
      document.body.appendChild(script);
    </script>
  </body>
</html>

WebPage/project/web/templates/main_template.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link text="text/css" rel="stylesheet" href="{{ url_for('static', filename='main_template.css') }}">
    <title>SeSac</title>
</head>
<body>
    <nav>
        <div class='nav_bar'>
            <a href = "{{ url_for('main.main_page') }}" class='main_link'>메인</a>
            <a href = "{{ url_for('quest.quest_list') }}" class='quest_link'>미션</a>
            <a href = "{{ url_for('main.ranking_page') }}" class='ranking_link'>랭킹</a>
            <a href = "{{ url_for('myinfo.setting_page') }}" class='setting_link'>설정</a>
            </div>
    </nav>
    <div class="upper-margin"></div>
    {% block content %}
    {% endblock %}

    {% include 'exp_modal.html' %}
</body>
</html>