WebPage/project/web/views/login_views.py
from flask import Blueprint, render_template, redirect, url_for, request, session,flash, g
from werkzeug.security import generate_password_hash, check_password_hash
from ..db import WebProject
from ..form import RegisterForm, LoginForm
from werkzeug.utils import redirect


bp = Blueprint('login', __name__, url_prefix='/login')
wp = WebProject.instance()
# 로그인
@bp.route('/', methods=['GET', 'POST'])
def login_page():
    form = LoginForm()
    if request.method == 'POST' and form.validate_on_submit(): 
        # 각 id랑 psw가 맞는지.
        userid = request.form['userid']
        userpw = request.form['userpw']

        is_exist = wp.send_query("SELECT EXISTS (SELECT id FROM user WHERE id = '{}') AS success".format(userid))

        if (is_exist[0]["success"]):
            user_pwd = wp.send_query("SELECT pwd FROM user WHERE id = '{}'".format(userid))
            if check_password_hash(user_pwd[0]['pwd'],userpw):
                session['logged_in'] = True
                session['id'] = userid
                return redirect(url_for("main.main_page"))
            else:
                flash('비밀번호 틀림')
                return redirect(url_for("login.login_page"))
        else:
            flash('존재하지 않는 아이디')
            return redirect(url_for("login.login_page"))
    else:
        # 이게 필요 하다.
        session['logged_in'] = False
        return render_template('login/login_page.html', form = form)

# 회원 가입
@bp.route('/register', methods=['GET', 'POST'])
def register_page():
    form = RegisterForm()
    if request.method == 'POST' and form.validate_on_submit():
        # real_name이 character name일 듯
        username= request.form['username']
        userid= request.form['userid']
        userpw= request.form['userpw']
        is_exist = wp.send_query("SELECT EXISTS (SELECT id FROM user WHERE id = '{}') AS success".format(userid))

        # 1. name이 같나 확인한다. (기존 db에서)
        if (is_exist[0]["success"]):
            # 2. 같으면 x 다시 돌아가게
            # 다시 돌아가게 짠다.
            flash('별명을 다시 입력하세요!','success')
            return redirect(url_for("login.register_page"))
        else:
            # 3. 다르면 그냥 회원가입 하게?? 가 맞는듯?
            # + db에 추가 하고 '/' 라우트로 이동.
            wp.send_query("INSERT INTO user(id, pwd, name) VALUES ('{}', '{}', '{}')".format(userid, generate_password_hash(userpw), username), commit=True)
            return redirect(url_for("login.login_page"))
    else:
        return render_template('login/register_page.html', form = form)
# 이용 약관
@bp.route('/terms', methods=['GET', 'POST'])
def terms():
    term_dict={}
    terms1 = wp.send_query("SELECT * FROM notice_board where title ='{}'".format('이용약관'))
    terms2 = wp.send_query("SELECT * FROM notice_board where title ='{}'".format('개인정보 취급방침'))
    term_dict['ret1'] = terms1[0]
    term_dict['ret2'] = terms2[0]
    return render_template('login/terms.html', terms = term_dict)

# 별명 회원가입 찾기
@bp.route('/find', methods=['GET','POST'])
def finder():
    if request.method == 'POST':
        if not (request.form['name']) or not (request.form['pwd']):
            flash('내용이 비어 있습니다.')
            return redirect(url_for('login.finder'))
        else:
            name = wp.send_query("SELECT id FROM user where name = '{}'".format(request.form['name']))
            if not (name):
                flash('내용이 틀림')
                return redirect(url_for('login.finder'))
            else:
                flash("별명은 {} 입니다.".format(name[0]['id']))            
                return redirect(url_for('login.login_page'))
    else:
        return render_template('login/find_id.html')

# 로그아웃
@bp.route('/logout/')
def logout():
    session.clear()
    session['logged_in'] = False
    return redirect(url_for("main.main_page"))

# 탈퇴
@bp.route('/withdraw/')
def withdraw():
    wp.send_query("DELETE from user where id='{}'".format(g.user['user_id']),commit=True)
    wp.send_query("DELETE from daily where user_id='{}'".format(g.user['user_id']),commit=True)
    wp.send_query("DELETE from solving where user_id='{}'".format(g.user['user_id']),commit=True)
    wp.send_query("DELETE from todo where user_id='{}'".format(g.user['user_id']),commit=True)
    return redirect(url_for("login.login_page"))



# 실행 전
@bp.before_app_request  
def load_logged_in_user():
    log = session.get('logged_in')
    if log:
        g.user = {'user_id': session.get('id')}
    else:
        g.user = None

WebPage/project/web/views/main_views.py
from flask import Blueprint, render_template, redirect, url_for, session, g, request,jsonify, flash
from ..db import WebProject, exp_manager
from datetime import date
import json
import random

bp = Blueprint('main', __name__, url_prefix='/')
wp = WebProject.instance()
em = exp_manager.instance()

@bp.route('/', methods = ['GET', 'POST'])
def main_page():
    if(request.method=="POST"):
        params = request.get_json()
        if(params["func"]=="store"):
            today = date.today().isoformat()
            act = "todo_complete" if params["is_complete"] else "todo_write"

            send = {"can_exp" : False, "exp" : 0}

            is_exists = wp.send_query("SELECT EXISTS (SELECT * FROM todo WHERE user_id = '{}' AND nth = {} AND date = '{}') AS success".format(g.user["user_id"], params["nth"], today))
            print(act)
            if(is_exists[0]["success"]):
                wp.send_query("UPDATE todo SET content='{}', is_complete={} WHERE user_id = '{}' AND nth = {} and date = '{}'".format(params["content"], params["is_complete"], g.user["user_id"], params["nth"], today), commit=True)
                if(act=="todo_complete"):
                    print("성공 exp 얻기")
                    send["can_exp"] = em.gain_exp(g.user["user_id"], act)
                    if(send["can_exp"]):
                        send["exp"] = em.exp_dict[act]
            else:
                wp.send_query("INSERT INTO todo(user_id, is_complete, content, nth, date) VALUES ('{}', {}, '{}', {}, '{}')".format(g.user["user_id"], params["is_complete"], params["content"], params["nth"], today), commit=True)
                if(act=="todo_write"):
                    print("작성 exp 얻기")
                    send["can_exp"] = em.gain_exp(g.user["user_id"], act)
                    if(send["can_exp"]):
                        send["exp"] = em.exp_dict[act]

        
        
        elif(params["func"]=="get"):
            send = wp.send_query("""WITH test AS
                (
                    SELECT 0 AS nth
                    UNION ALL
                    SELECT 1 AS nth
                    UNION ALL
                    SELECT 2 AS nth
                    UNION ALL
                    SELECT 3 AS nth
                    UNION ALL
                    SELECT 4 AS nth
                )
                SELECT test.nth, IFNULL(todo.is_complete, -1) AS is_complete , IFNULL(todo.content, "") AS content FROM test LEFT JOIN todo ON test.nth = todo.nth AND todo.user_id = '{}' AND todo.date = '{}' ORDER BY nth;
                """.format(g.user["user_id"], params["date"]))
        
        return json.dumps(send)
    

    log = session.get('logged_in')
    if log:
        # 로그인 중이면
        em.daily_exist(g.user["user_id"])
        main_data = {}
        # args id 가 있을 때
        if request.args.get('id'):
           back_id = request.args.get('id', type=int)
           wp.send_query("update user set background_id={} where id='{}';".format(back_id,g.user["user_id"]), commit=True)
        # args snow 가 있을 때
        elif request.args.get('snow'):
           snow_id = request.args.get('snow', type=int)
           wp.send_query("update user set snow={} where id='{}';".format(snow_id,g.user["user_id"]), commit=True)
            
        back_snow = wp.send_query("SELECT background_id, snow FROM user WHERE id = '{}'".format(g.user["user_id"]))
        back_id = back_snow[0]['background_id']
        snow_id = back_snow[0]['snow']
        
        result = wp.send_query("SELECT user_Lv, user_Exp FROM user WHERE id = '{}'".format(g.user["user_id"]))
        main_data["lv"] = result[0]["user_Lv"]
        main_data["exp"] = result[0]["user_Exp"]

        main_data["imgview"] = random.randrange(1,3)

        main_data["max_exp"] = em.lvup_dict[main_data["lv"]]
        main_data['background_id'] = back_id
        main_data['snow_id'] = snow_id
        today = date.today().isoformat()
        main_data["mission"] = wp.send_query("SELECT quest_solve FROM daily WHERE user_id = '{}' AND date = '{}'".format(g.user["user_id"], today))[0]["quest_solve"]

        two = wp.send_query('select content from notice_board')
        li = [i['content'] for i in two]
        main_data['li'] = li
        
        return render_template('main/main_page.html', main_data=main_data)
    else:
        # 로그인 정보가 없으면
        return redirect(url_for("login.login_page"))

        
@bp.route('/ranking', methods=['GET', 'POST'])
def ranking_page():
    rank_dict = {}
    number = 10
    #현재 페이지
    page = request.args.get('page', type=int, default=1)
    first_number = (page-1) *number
    last_number =  (page*number)
    ranking = wp.send_query("SELECT id, user_Lv, user_Exp FROM user ORDER BY user_Lv DESC,user_Exp DESC")
    
    max_page = (len(ranking) - 1) // number + 1

    item = ranking[first_number:last_number]
    
    rank_dict['item'] = item
    rank_dict['max_page'] = list(range(1,max_page+1))
    rank_dict['page'] = page
    for j,i in enumerate(ranking):
        if g.user['user_id'] == i['id']:
            rank_dict['myinfo'] = j+1
            rank_dict['mypage'] = int((j //10) +1)
    
    if request.method == 'POST':
        params = request.get_json()

        for ret1,ret2 in enumerate(ranking):
            te = True
            if params['value'] == ret2['id']:
                te = False
                print(ret1)
                user_page = int((ret1 //10) +1)
                data = {'user_page': user_page}
                return jsonify(data)
        if te:
            flash('다시하세요')

            return redirect(url_for('main.ranking_page'))
            

    return render_template('main/ranking_page.html',user_rank = rank_dict)


@bp.route('/gg', methods = ['GET'])
def test():

    return render_template('main/test.html', datas = data)

WebPage/project/web/views/myinfo_views.py
from flask import Blueprint, render_template, redirect, url_for, g, request, flash
from ..db import WebProject
from werkzeug.security import check_password_hash,generate_password_hash
from ..form import Trypwd, Enroll

bp = Blueprint('myinfo', __name__, url_prefix='/myinfo')
wp = WebProject.instance()


@bp.route('/')
def setting_page():
    data =g.user["user_id"]
    return render_template('myinfo/setting_page.html', data = data)

@bp.route('/passcheck', methods=['GET', 'POST'])
def password():
    form = Trypwd()
    data = g.user["user_id"]
    if request.method == 'POST' and form.validate_on_submit():
        userpw = request.form['userpw2']
        user_pwd = wp.send_query("SELECT pwd FROM user WHERE id = '{}'".format(g.user['user_id']))
        
        if check_password_hash(user_pwd[0]['pwd'],userpw):
            print('여기까지 왔다요')
            return redirect(url_for("myinfo.infomodify"))
        
        else:
            flash('비밀번호 틀림')
            return redirect(url_for("myinfo.password"))

    else:
        return render_template('myinfo/myinfo_passcheck.html', form=form, data = data)
    
@bp.route('/infomodify', methods=['GET', 'POST'])
def infomodify():
    if(request.method == 'POST'):
        params = request.get_json()
        if len(params['value']) == 0:
            flash('다시 입력해 주세요')
            return redirect(url_for("myinfo.infomodify"))
        else:
            if params['column'] == 'name':
                wp.send_query("UPDATE user SET {} = '{}' WHERE id='{}'".format(params['column'], params['value'], g.user['user_id']), commit=True)
            else:
                wp.send_query("UPDATE user SET {} = '{}' WHERE id='{}'".format(params['column'], generate_password_hash(params['value']), g.user['user_id']), commit=True)
            return redirect(url_for("myinfo.infomodify"))
    user_info = {}
    user = wp.send_query("select * from user where id='{}'".format(g.user['user_id']))
    user_info['user_name'] = user[0]['name']
    user_info['user_id'] = user[0]['id']
    user_info['user_pwd']= user[0]['pwd']
    return render_template('myinfo/myinfo_modify.html', user_info = user_info)





@bp.route('/notice', methods=['GET'])
def notice():
    notice_dict = {}
    notice = wp.send_query("SELECT * FROM notice_board ORDER BY date DESC")
    notice_dict['item'] = notice
    user = wp.send_query("select * from user where id = '{}'".format(g.user['user_id']))
    notice_dict['admin'] = user[0]['admin']
    return render_template('myinfo/myinfo_notice.html',notice = notice_dict)


@bp.route('/content/<int:content_id>', methods=['GET'])
def content(content_id):
    content_dict = {}
    
    notice = wp.send_query("SELECT * from notice_board ORDER BY date DESC")
    page_list = [i['id'] for i in notice]
    content_dict['page_list'] = page_list
    content_dict['page'] = content_id
    
    content = wp.send_query("SELECT * from notice_board where id ={}".format(content_id))
    content_dict['content'] = content[0]
    return render_template('myinfo/myinfo_notice_content.html',contented=content_dict)

# 게시글 등록
@bp.route('/enroll', methods=['GET', 'POST'])
def enroll():
    form = Enroll()
    if request.method == 'POST' and form.validate_on_submit():  
        title = request.form['title']
        content = request.form['content']
        print(title,content)
        wp.send_query("INSERT INTO notice_board(title, content) VALUES ('{}', '{}')".format(title,content), commit=True)
        
        return redirect(url_for("myinfo.notice"))
    
    else:
        return render_template('myinfo/myinfo_notice_enroll.html', form=form)
    
# 삭제
@bp.route('/delete/<int:content_id>', methods=['GET'])
def delete(content_id):
    wp.send_query("DELETE FROM notice_board WHERE id = {}".format(content_id), commit=True)
    return redirect(url_for("myinfo.notice"))


@bp.route('/modify/<int:content_id>', methods=['GET','POST'])
def modify(content_id):
    content = wp.send_query("SELECT * from notice_board where id ={}".format(content_id))
    print('modify의')
    before = [content[0]['title'],content[0]['content']]
    if request.method == 'POST':
        title = request.form['title']
        contents = request.form['content']
        after = [title, contents]
        
        if before != after:
            wp.send_query("update notice_board set title='{}', content='{}' where id={};".format(title,contents,content_id), commit=True)
            
        return redirect(url_for("myinfo.notice"))
    else:
        return render_template('myinfo/myinfo_notice_modify.html',content=content[0])

WebPage/project/web/templates/myinfo/myinfo_modify.html
{% extends 'main_template.html' %}
{% block content %}
    <link text="text/css" rel="stylesheet" href="{{ url_for('static', filename='myinfo/myinfo.css') }}">
    <script defer src="{{ url_for('static', filename='myinfo/myinfo_modify.js') }}"></script>
<body>
    <div class="myinfomodify">
        <div class="myinfomodify_top">
            <div class="myinfomodify_name">내 정보 수정</div>            
        </div>
        <div class="myinfomodify_content">
            <div class="myinfomodify_content_fullset">
                <div class="myinfomodify_content_title">
                    이름
                </div>
                <div class="myinfomodify_content_set">                    
                    <div class="myinfomodify_content_sub">{{user_info['user_name']}}</div>
                    <input type="button" class="myinfomodify_submit" id="myinfomodify_name" value="변경하기"/>
                </div>                
            </div>

            <div class="myinfomodify_content_fullset">                
                <div class="myinfomodify_content_title">
                    비밀번호
                </div>
                <div class="myinfomodify_content_set">
                    <div class="myinfomodify_content_sub">********</div>
                    <input type="button" class="myinfomodify_submit" id="myinfomodify_password" value="변경하기"/>
                </div>                
            </div>                        

            <div class="myinfomodify_content_fullset">                
                <div class="myinfomodify_content_title">
                    배경 선택
                </div>
                <div class = "totback">
                    <a href="{{url_for('main.main_page',id = 1)}}">
                        <img src="{{url_for('static',filename='myinfo/myinfo_ui/backimg.jpeg')}}" class="char">
                    </a>

                    <a href="{{url_for('main.main_page',id = 2)}}">
                        <img src="{{url_for('static',filename='myinfo/myinfo_ui/backimg2.jpeg')}}" class="char">
                    </a>
                    <a href="{{url_for('main.main_page',id = 3)}}">
                        <img src="{{url_for('static',filename='myinfo/myinfo_ui/backimg3.jpeg')}}" class="char">
                    </a>
                </div>
            </div>    
            <div class="myinfomodify_content_fullset">                
                <div class="myinfomodify_content_title">
                    
                        <div class = "myinfomodify_content_set2">
                            <div class="margins">눈 내리기 적용</div>
                            <button class = "btns" onclick = "location.href='{{url_for('main.main_page',snow = 1)}}'">on</button>
                            <button class = "btns" onclick = "location.href='{{url_for('main.main_page',snow = 0)}}'" style = "margin-left: 28px;">off</button>
                        </div>
                    </div>
            </div>   
            <div class="myinfomodify_content_fullset">                
                <a href="{{url_for('login.withdraw')}}" class="myinfomodify_content_title" style="color: darkgray; font-weight: lighter;">
                    회원탈퇴 하기
                </a>                
                <div class="myinfomodify_content_title" style="color: darkgray; font-weight: lighter; font-size: 12px;">클릭하시면 바로 탈퇴되니 신중히 눌러주시기 바랍니다.</div>
            </div>        
        </div>
    </div>

</body>
{% endblock %}

WebPage/project/web/templates/myinfo/myinfo_notice.html
{% extends 'main_template.html' %}
{% block content %}
<link text="text/css" rel="stylesheet" href="{{ url_for('static', filename='./myinfo/myinfo_notice.css') }}">
<body>
    <div class="notice">
        <div class="notice_top">            

            <div class='notice_name'>공지사항
            {%if notice['admin'] == 1%}
                <a href="{{ url_for('myinfo.enroll') }}">등록</a>            
            {%endif%}
            </div>            
        </div>

        <div class="notice_contents">
            {%for i in notice['item']%}
            <div class="notice_content">
                <div class="notice_datetime"> {{i['date']}}</div>
                <div class="notice_sub">
                    <a href="{{ url_for('myinfo.content', content_id = i['id'] ) }}" class="textcon" >{{i['title']}}</a>
                     
                        {%if notice['admin'] == 1%}                        
                        <div class="admin_modify">
                            <a class = "delete" href="javascript:void(0)" data-uri="{{ url_for('myinfo.delete', content_id=i['id']) }}">삭제</a>                            
                            <a href="{{ url_for('myinfo.modify', content_id = i['id'] ) }}">수정</a>                        
                        </div>
                        {%endif%}                        
                </div>
            </div>
            {% endfor %}
        </div> 
    </div>    




    <!--script도 static/ exp modal.js랑 충돌 난다.-->
    <script type='text/javascript'>
        const delete_elements = document.getElementsByClassName("delete");
        Array.from(delete_elements).forEach(function(element) {
            element.addEventListener('click', function() {
                if(confirm("정말로 삭제하시겠습니까?")) {
                    location.href = this.dataset.uri;
                };
            });
        });
    </script>

</body>
{% endblock %}

WebPage/project/web/templates/myinfo/myinfo_notice_content.html
{% extends 'main_template.html' %}
{% block content %}
<link text="text/css" rel="stylesheet" href="{{ url_for('static', filename='./myinfo/myinfo_notice_content.css') }}">
<body>
    <div class = "notice">
        <header>
            <div class = "headers"></div>
            <div class="head">공지사항</div>
            <div class="border"></div>
        </header>

        <main>
            <div class="content">

                <div class="li">
                    <div class="datetime"> {{contented['content']['title']}}</div>
                    <div class="datetime"> {{contented['content']['date']}}</div>
                    <div class="textcon">{{contented['content']['content']}}</div>
                </div>
            </div>
        </main>

        <footer class="pagecon">
            {% if contented.page_list[0]==contented.page %}
                <div class="next">
                    <a href="{{ url_for('myinfo.content', content_id = contented.page_list[1] ) }}" class = "text">다음글</a>
                </div>

                <div class="prev">
                    <span>이전글</span>
                    <span>(없음)</span>
                </div>
            {% elif contented.page_list[-1]==contented.page %}
                <div class="next">
                    <span>다음글</span>
                    <span>(없음)</span>
                </div>

                <div class="prev">
                    <a href="{{ url_for('myinfo.content', content_id = contented.page_list[-2] ) }}" class = "text">이전글</a>
                </div>
            {% else %}
                <div class="next">
                    <a href="{{ url_for('myinfo.content', content_id = contented.page_list[contented.page_list.index(contented.page)+1] ) }}" class = "text">다음글</a>
                </div>

                <div class="prev">
                    <a href="{{ url_for('myinfo.content', content_id = contented.page_list[contented.page_list.index(contented.page)-1] ) }}" class = "text">이전글</a>
                </div>
            {% endif %}
        </footer>
    </div>
</body>
{% endblock %}

WebPage/project/web/templates/myinfo/myinfo_notice_enroll.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>공지사항</title>
    <link text="text/css" rel="stylesheet" href="{{ url_for('static', filename='myinfo/myinfo_enroll.css') }}">

</head>
<body>
    <div class="board_wrap">
        <div class="board_title">
            <strong style = "margin-left:6px;">공지사항 등록</strong>
        </div>

        <form method="post" class="my-3">
            <div class="board_write_wrap">
                <div class="board_write">
                    <div class="title">
                        <dl>        
                            <dd>
                                <label for="title"></label>
                                <input type="text" placeholder="제목 입력" name="title" id="title"/>
                            </dd>
                        </dl>
                    </div>

                    <div class="cont">
                        <label for="content"></label>
                        <textarea name="content" id="content" placeholder="내용 입력"></textarea>
                    </div>

                </div>
                
                <div class="bt_wrap">
                    <button type="submit"class="tododo">등록</button>
                    <a href="{{ url_for('myinfo.notice') }}">취소</a>
                </div>
            </div>

            <!-- 필드 / flash 오류 -->
            {{ form.csrf_token }}
            <!--{% include "form_errors.html" %}-->
            {% if form.errors %}
            <div class="alert alert-danger" role="alert">
                {% for field, errors in form.errors.items() %}
                    <strong id = 'te' style = "font-size: 2rem;">{{ form[field].label }} 입력해주세요.</strong> <br>
                {% endfor %}
            </div>
            {%endif %}
        </form>

    </div>
</body>
</html>

WebPage/project/web/templates/myinfo/myinfo_notice_modify.html
{% extends 'main_template.html' %}
{% block content %}
<link text="text/css" rel="stylesheet" href="{{ url_for('static', filename='myinfo/myinfo_enroll.css') }}">

<body>
    <div class="board_wrap">
        <div class="board_title">
            <strong style = "margin-left:6px;">공지사항 수정</strong>
        </div>
        <form method="post" class="my-3">
            <div class="board_write_wrap">
                <div class="board_write">
                    <div class="title">
                        <dl>        
                            <dd>
                                <input type = 'text' class="datetime" value = "{{content['title']}}" name = 'title'/> 
                            </dd>
                        </dl>
                    </div>

                    <div class="cont">
                        <textarea type = 'text' class="textcon" name = 'content'>{{content['content']}}</textarea>
                    </div>

                </div>
                
                <div class="bt_wrap">
                    <button type="submit" class="tododo">저장하기</button>
                    <a href="{{ url_for('myinfo.notice') }}">취소</a>
                </div>
            </div>
        </form>

    </div>
</body>




{% endblock %}

WebPage/project/web/templates/myinfo/myinfo_passcheck.html
{% extends 'main_template.html' %}
{% block content %}
<link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet" />
<link href="https://fonts.googleapis.com/css?family=Montserrat&display=swap" rel="stylesheet" />
<link text="text/css" rel="stylesheet" href="{{ url_for('static', filename='./myinfo/myinfo.css') }}">
<script src = "{{url_for('static',filename='./login/login_form.js')}}"> </script>

<body>
    <div class="myinfo">
        <div class="myinfopasscheck_top">
            <div class="myinfopasscheck_name">비밀번호 재확인</div>
            <div>회원님의 소중한 정보를 위해 비밀번호를 재확인하고있어요.</div>
        </div>
        <div class="myinfopasscheck_content">
            <div class="myinfopasscheck_content_set">
                <div class="myinfopasscheck_content_title">
                    별명
                </div>
                <div class="myinfopasscheck_content_sub">
                    {{data}}
                </div>
            </div>
            <form action="{{ url_for('myinfo.password') }}" method="post">

                <div class="myinfopasscheck_content_set">
                    
                    <div class="myinfopasscheck_content_title" >
                        비밀번호
                    </div>

                    <label for="userpw2"></label>
                    <div class="myinfopasscheck_content_sub">
                        <input type="password" name="userpw2"/>
                        <div class = "validate"  id = 'validate' name='비밀번호'> </div>
                    </div>
                </div>   

                <div class="myinfopasscheck_content_set">
                    <input type="submit" class="myinfopasscheck_submit" value="다음"/>
                </div>    
                <!-- 필드 / flash 오류 -->
                {{ form.csrf_token }}
                {% include "form_errors.html" %}

            </form>

        </div>
    </div>
</body>
{% endblock %}

WebPage/project/web/templates/myinfo/setting_page.html
{% extends 'main_template.html' %}
{% block content %}
<script> document.querySelector(".setting_link").classList.add("selected") </script>
<link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet" />
<link href="https://fonts.googleapis.com/css?family=Montserrat&display=swap" rel="stylesheet" />
<link text="text/css" rel="stylesheet" href="{{ url_for('static', filename='./myinfo/myinfo.css') }}">

<body>
    <div class="myinfo">
        <div class="myinfo_top">            
            <div class="myinfo_name">{{data}} 님</div>            
        </div>

        <div class="myinfo_content">
            
            <div class="myinfo_content_set">
                <div class="myinfo_content_title">
                    내계정                    
                </div>
                <a href="{{ url_for('myinfo.password') }}" class="myinfo_content_sub">
                    설정
                </a>
            </div>

            <div class="myinfo_content_set">
                <div class="myinfo_content_title">
                    ABOUT Growupteam
                </div>
                <a href="{{ url_for('myinfo.notice') }}" class="myinfo_content_sub">
                    공지사항
                </a>
            </div>   

            <div class="myinfo_content_set">
                <a href="{{ url_for('login.logout') }}" class="myinfo_logout">
                    로그아웃 하기
                </a>
            </div>   

        </div>
    </div>
    
</body>
{% endblock %}