WebPage/project/web/views/login_views.py
from flask import Blueprint, render_template, redirect, url_for, request, session,flash, g
from werkzeug.security import generate_password_hash, check_password_hash
from ..db import WebProject
from ..form import RegisterForm, LoginForm
from werkzeug.utils import redirect


bp = Blueprint('login', __name__, url_prefix='/login')
wp = WebProject.instance()
# 로그인
@bp.route('/', methods=['GET', 'POST'])
def login_page():
    form = LoginForm()
    if request.method == 'POST' and form.validate_on_submit(): 
        # 각 id랑 psw가 맞는지.
        userid = request.form['userid']
        userpw = request.form['userpw']

        is_exist = wp.send_query("SELECT EXISTS (SELECT id FROM user WHERE id = '{}') AS success".format(userid))

        if (is_exist[0]["success"]):
            user_pwd = wp.send_query("SELECT pwd FROM user WHERE id = '{}'".format(userid))
            if check_password_hash(user_pwd[0]['pwd'],userpw):
                session['logged_in'] = True
                session['id'] = userid
                return redirect(url_for("main.main_page"))
            else:
                flash('비밀번호 틀림')
                return redirect(url_for("login.login_page"))
        else:
            flash('존재하지 않는 아이디')
            return redirect(url_for("login.login_page"))
    else:
        # 이게 필요 하다.
        session['logged_in'] = False
        return render_template('login/login_page.html', form = form)

# 회원 가입
@bp.route('/register', methods=['GET', 'POST'])
def register_page():
    form = RegisterForm()
    if request.method == 'POST' and form.validate_on_submit():
        # real_name이 character name일 듯
        username= request.form['username']
        userid= request.form['userid']
        userpw= request.form['userpw']
        is_exist = wp.send_query("SELECT EXISTS (SELECT id FROM user WHERE id = '{}') AS success".format(userid))

        # 1. name이 같나 확인한다. (기존 db에서)
        if (is_exist[0]["success"]):
            # 2. 같으면 x 다시 돌아가게
            # 다시 돌아가게 짠다.
            flash('별명을 다시 입력하세요!','success')
            return redirect(url_for("login.register_page"))
        else:
            # 3. 다르면 그냥 회원가입 하게?? 가 맞는듯?
            # + db에 추가 하고 '/' 라우트로 이동.
            wp.send_query("INSERT INTO user(id, pwd, name) VALUES ('{}', '{}', '{}')".format(userid, generate_password_hash(userpw), username), commit=True)
            return redirect(url_for("login.login_page"))
    else:
        return render_template('login/register_page.html', form = form)
# 이용 약관
@bp.route('/terms', methods=['GET', 'POST'])
def terms():
    term_dict={}
    terms1 = wp.send_query("SELECT * FROM notice_board where title ='{}'".format('이용약관'))
    terms2 = wp.send_query("SELECT * FROM notice_board where title ='{}'".format('개인정보 취급방침'))
    term_dict['ret1'] = terms1[0]
    term_dict['ret2'] = terms2[0]
    return render_template('login/terms.html', terms = term_dict)

# 별명 회원가입 찾기
@bp.route('/find', methods=['GET','POST'])
def finder():
    if request.method == 'POST':
        if not (request.form['name']) or not (request.form['pwd']):
            flash('내용이 비어 있습니다.')
            return redirect(url_for('login.finder'))
        else:
            name = wp.send_query("SELECT id FROM user where name = '{}'".format(request.form['name']))
            if not (name):
                flash('내용이 틀림')
                return redirect(url_for('login.finder'))
            else:
                flash("별명은 {} 입니다.".format(name[0]['id']))            
                return redirect(url_for('login.login_page'))
    else:
        return render_template('login/find_id.html')

# 로그아웃
@bp.route('/logout/')
def logout():
    session.clear()
    session['logged_in'] = False
    return redirect(url_for("main.main_page"))

# 탈퇴
@bp.route('/withdraw/')
def withdraw():
    wp.send_query("DELETE from user where id='{}'".format(g.user['user_id']),commit=True)
    wp.send_query("DELETE from daily where user_id='{}'".format(g.user['user_id']),commit=True)
    wp.send_query("DELETE from solving where user_id='{}'".format(g.user['user_id']),commit=True)
    wp.send_query("DELETE from todo where user_id='{}'".format(g.user['user_id']),commit=True)
    return redirect(url_for("login.login_page"))



# 실행 전
@bp.before_app_request  
def load_logged_in_user():
    log = session.get('logged_in')
    if log:
        g.user = {'user_id': session.get('id')}
    else:
        g.user = None

WebPage/project/web/templates/login/find_id.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link text="text/css" rel="stylesheet" href="{{ url_for('static', filename='./login/find_id.css') }}">
</head>
<body>

    {% for message in get_flashed_messages() %}
        <div class="alert alert-danger" role="alert">
            <script>alert("{{message}}")</script>
        </div>
    {% endfor %}

    <div class="all">
        <div class="title">
            <h2>별명 찾기</h2>
            <p class="font">회원가입 시, 입력하신 이름, 비밀번호로
                별명을 확인하실 수 있습니다.</p>
        </div>    
        <div class="inputs">
        <form action="{{ url_for('login.finder') }}" method="post">
            <input type="text" placeholder="이름" class="inputtext" name = 'name'/>
            
        </div>
        <div class="inputs">
            <input type="password" placeholder="비밀번호" class="inputtext" name = 'pwd'/>
        </div>
    </div>
    <div class="borderline" style="border: 1px solid black; "></div>
    <div class="btn_box">
        <button type = 'submit' class="btn">별명 찾기</button>
    </div>
    </form>
</body>
</html>

WebPage/project/web/templates/login/login_page.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet" />
    <link rel = 'stylesheet' href = "{{url_for('static',filename='./login/login_page.css')}}"/>
    <script src = "{{url_for('static',filename='./login/login_form.js')}}"> </script>
    <title>로그인</title>
</head>

<body>
    <div class="divbody">
        
           
        <header class = "displaycenter">
            <div class="title">새싹이 키우기</div>
        </header>
             <div class = "displaycenter">
            <img src="{{url_for('static',filename='./login/login_ui/login_sprout.gif')}}" class="char">
            </div>
        <section>
            <form action="{{ url_for('login.login_page') }}" method="post">
            <div class="divone">

                <div class="display">
                    <span class="textmargin fonts">별명</span>
                    <div class = "displaycenter">
                        <label for="userid"></label>
                        <div class = "divdisplay">

                            <input class="inputbox" name = 'userid'/>
                            <div class = "validate"  id = 'validate' name='별명'> </div>

                        </div>
                    </div>
                
                </div>

                <div class="display"> 
                    <span class="textmargin fonts">비밀번호</span>

                    <div class = "displaycenter">
                        <label for="userpw"></label>
                        <div class = "divdisplay"> 

                            <input class="inputbox" name = 'userpw' type="password"/>
                            <div class = "validate" id = 'validate' name='비밀번호'> </div>

                        </div>
                    </div>

                </div>

            </div>

            <div class = "display">
                <div class = "displaycenter">
                <input type = "submit" class="login" style = "margin-bottom:16px; font-family: 'EF_Diary';" value='로그인 하기'/>
                </div>

                <!-- 필드 / flash 오류 -->
                {{ form.csrf_token }}
                {% include "form_errors.html" %}

            </form>

                <div class = "displaycenter">
                    <div>
                        <div style ="width:100%">
                            <a class="a fonts" href="{{ url_for('login.register_page') }}">회원가입</a>
                            <a>/</a>
                            <a class="a fonts" href="{{ url_for('login.finder') }}">별명 ∙ 비밀번호 찾기</a>
                        </div>
                    </div>

                </div>
            </div>
        </section>

    </div>
</body>

</html>

WebPage/project/web/templates/login/register_page.html
 
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel = 'stylesheet' href = "{{url_for('static',filename='./login/register_page.css')}}"/>
    <link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet" />
    <title>회원가입</title>
    <script src = "{{url_for('static',filename='./login/login_form.js')}}"> </script>
</head>
<body>
    <header height = "100px">
        <div style = "height: 100px">
            <img src="{{url_for('static',filename='./login/login_ui/register_sprout.gif')}}" width="110px" height = "100%" style = "margin-right:5px">
        </div>
    </header>

    <section>
      <form action="{{ url_for('login.register_page') }}" method="post">
        <div class="join">
            <div class="join_title">회원가입</div>        
            <div class="join_input">            
                <label for="username"></label>
                <input class="join_inputBox" placeholder="이름" type="text" name = 'username' >
                <div class = "validate" id = 'validate' name='이름'> </div>

                <label for="userid"></label>
                <input class="join_inputBox" placeholder="별명" type="text" name = 'userid'>
                <div class = "validate"  id = 'validate' name='별명'> </div>

                <label for="userpw"></label>
                <input class="join_inputBox" placeholder="비밀번호" type="password" name = 'userpw'>
                <div class = "validate" id = 'validate' name='비밀번호'> </div>
            </div>            
            
            <div class="join_submit">
                <input class="join_submitButton" type = 'submit' style = "border:0px"value = "가입 완료" />

                {{ form.csrf_token }}
                {% include "form_errors.html" %}
                
      </form>

                <p style="font-size:11px;">가입하면
                    <a href="{{ url_for('login.terms') }}" style="color:#4DAB3C;">이용약관</a>과
                    <a href="{{ url_for('login.terms') }}" style="color:#4DAB3C;">개인정보취급방침</a>에 동의 한 것으로 봅니다.
                </p>

            </div>
        </div>  
    </section>
</body>
</html> 

WebPage/project/web/templates/login/terms.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css?family=Montserrat&display=swap" rel="stylesheet" />
    <link text="text/css" rel="stylesheet" href="{{ url_for('static', filename='./login/terms.css') }}">
    <title>SeSac</title>
</head>
<body>
    <div class="terms">
        <div class="terms_top">
            <div class="terms_name">{{terms['ret1']['title']}}</div>            
        </div>
        <div class="terms_content">            
            <div class="terms_content_date">
                작성일 : {{terms['ret1']['date']}}
            </div>
            <div class="terms_content_sub">                        
                {{terms['ret1']['content']}}
            </div>                
        </div>
        <div class="terms_top">
            <div class="terms_name">{{terms['ret2']['title']}}</div>            
        </div>
        <div class="terms_content">
            <div class="terms_content_date">
                작성일 : {{terms['ret2']['date']}}
            </div>
            <div class="terms_content_sub">                        
                {{terms['ret2']['content']}}
            </div>                
            </div>       
        </div>
    </div>
    
</body>
</html>